"""PM-style markdown memo combining capacity curve, crowding, stress, policy."""
from __future__ import annotations

from pathlib import Path

import pandas as pd

from ..capacity.curve import CapacityCurve
from ..capacity.multi_factor import AllocationResult
from ..crowding.composite import CrowdingScore
from ..policy.checkpoints import CapacityCheckpoint
from ..policy.search import PolicyResult
from ..stress.scenarios import StressResult


def _fmt_aum(aum: float, unit_value: float, unit_label: str) -> str:
    return f"{aum / unit_value:,.1f} {unit_label}" if aum else "—"


def write_memo(
    *,
    output_path: str | Path,
    factor_curves: dict[str, CapacityCurve],
    crowding_scores: dict[str, CrowdingScore],
    stress_results: dict[str, StressResult],
    policy_results: dict[str, PolicyResult],
    checkpoints: dict[str, list[CapacityCheckpoint]],
    multi_factor: AllocationResult | None,
    unit_value: float,
    unit_label: str,
):
    lines = []
    lines.append("# Factor Capacity & Crowding Monitor — PM Memo\n")
    lines.append("> Auto-generated by `fcm.scripts.run_demo`. Do not edit by hand.\n")

    lines.append("## Executive summary\n")
    rows = []
    for name in factor_curves:
        c = factor_curves[name]
        cs = crowding_scores.get(name)
        st = stress_results.get(name)
        rows.append({
            "Factor": name,
            "Safe capacity": _fmt_aum(c.safe_capacity() or 0, unit_value, unit_label),
            "IR≥0.5 capacity": _fmt_aum(c.ir_threshold_capacity(0.5) or 0, unit_value, unit_label),
            "Stress safe": _fmt_aum(st.stressed.safe_capacity() or 0, unit_value, unit_label) if st else "—",
            "Crowding": f"{cs.latest_composite:.0f} ({cs.alert_level})" if cs else "—",
            "Best policy": (
                f"{policy_results[name].best_freq}/{int(policy_results[name].best_buffer_bps)}bps"
                if name in policy_results else "—"
            ),
        })
    lines.append(pd.DataFrame(rows).to_markdown(index=False))
    lines.append("")

    if multi_factor is not None and multi_factor.weights:
        lines.append("\n## Multi-factor capacity allocation\n")
        rows = []
        for k, w in multi_factor.weights.items():
            rows.append({
                "Factor": k,
                "Weight": f"{w * 100:.1f}%",
                "AUM": _fmt_aum(multi_factor.aum_allocations[k], unit_value, unit_label),
                "Net IR": f"{multi_factor.factor_irs[k]:.2f}",
            })
        lines.append(pd.DataFrame(rows).to_markdown(index=False))
        lines.append(
            f"\nTotal expected net return: "
            f"{multi_factor.expected_net_return_pct * 100:.2f}% / "
            f"{multi_factor.expected_net_return_dollars / unit_value:,.1f} {unit_label}.\n"
        )

    for name, curve in factor_curves.items():
        lines.append(f"\n## {name}\n")
        cs = crowding_scores.get(name)
        st = stress_results.get(name)
        cps = checkpoints.get(name, [])
        pol = policy_results.get(name)

        lines.append("### Capacity curve\n")
        df = curve.to_frame()[["aum", "gross_ir", "net_ir", "total_cost_bps",
                                "max_exec_days", "max_participation", "zone"]]
        df = df.copy()
        df["aum"] = df["aum"].apply(lambda x: _fmt_aum(x, unit_value, unit_label))
        df["max_participation"] = df["max_participation"].apply(lambda x: f"{x*100:.1f}%")
        lines.append(df.to_markdown(index=False))
        safe = curve.safe_capacity() or 0
        ir50 = curve.ir_threshold_capacity(0.5) or 0
        lines.append(
            f"\n**Safe capacity:** {_fmt_aum(safe, unit_value, unit_label)}; "
            f"**IR≥0.5 capacity:** {_fmt_aum(ir50, unit_value, unit_label)}.\n"
        )

        if st:
            lines.append("\n### Stress capacity\n")
            stress_safe = st.stressed.safe_capacity() or 0
            lines.append(
                f"Under widened spreads (q={0.99}), shrunken ADV, fattened vol and "
                f"+200bps borrow, safe capacity drops to **{_fmt_aum(stress_safe, unit_value, unit_label)}**. "
                f"Hard cap should be the minimum of normal and stressed safe capacity.\n"
            )
            if st.redemption:
                rdf = pd.DataFrame(
                    [(_fmt_aum(a, unit_value, unit_label), f"{c:.0f} bps")
                     for a, c in st.redemption.items()],
                    columns=["AUM", "Unwind cost (5d, 30% redemption)"]
                )
                lines.append(rdf.to_markdown(index=False))
                lines.append("")

        if cs:
            lines.append("\n### Crowding\n")
            lines.append(f"Composite score: **{cs.latest_composite:.0f}** "
                         f"(alert level: **{cs.alert_level}**).\n")
            comp_rows = [
                {"Component": k, "Score": f"{v:.0f}"}
                for k, v in cs.latest.items()
            ]
            lines.append(pd.DataFrame(comp_rows).to_markdown(index=False))
            lines.append("")

        if pol:
            lines.append("\n### Operating policy\n")
            lines.append(
                f"At target AUM = {_fmt_aum(pol.target_aum, unit_value, unit_label)} "
                f"the optimal policy is: rebalance **{pol.best_freq}**, "
                f"no-trade buffer **{int(pol.best_buffer_bps)} bps** → "
                f"net IR ≈ **{pol.best_net_ir:.2f}**.\n"
            )
            grid = pol.grid.copy()
            grid["net_ir"] = grid["net_ir"].round(2)
            grid["gross_ir"] = grid["gross_ir"].round(2)
            grid["total_cost_bps"] = grid["total_cost_bps"].round(0)
            lines.append(grid.to_markdown(index=False))
            lines.append("")

        if cps:
            lines.append("\n### Capacity checkpoints\n")
            cp_rows = [
                {"% of safe": f"{c.pct_of_safe*100:.0f}%",
                 "AUM": _fmt_aum(c.aum, unit_value, unit_label),
                 "Action": c.rule}
                for c in cps
            ]
            lines.append(pd.DataFrame(cp_rows).to_markdown(index=False))
            lines.append("")

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    return out
